# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
title: openXpert
author: Christiam Rey
email: christiamrey@openxpert.com
description: >-
  Somos su socio estratégico en el mundo digital y tecnológico. Con una sólida trayectoria 
  en desarrollo web y móvil, y una profunda experiencia en infraestructura informática, 
  ofrecemos soluciones integrales que impulsan el crecimiento y la eficiencia de su negocio.

phone: "+54 3447 434659"

# URL settings
domain: creyco.github.io
url: https://creyco.github.io
baseurl: /openxpert/

# Social
twitter_username: openxpert
github_username: creyco

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# Permalinks
permalink: /blog/:title/

# Markdown
markdown: kramdown

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
